import type { Metadata } from "next";
import "./globals.css";
import { outfit } from "@/lib/fonts";
import { NextSessionProvider } from "@/contexts/session-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Techwards-ATS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <NextSessionProvider>
          {children}
          <Toaster />
        </NextSessionProvider>
      </body>
    </html>
  );
}
